import { ArmyHierarchy, ArmyAgent, Squad } from '@/types/agent-army'

// Mock data for the Agent Army
export const mockArmyData: ArmyHierarchy = {
  commander: {
    id: 'commander-1',
    name: 'Bubba',
    role: 'commander',
    skills: ['Strategic Planning', 'Team Coordination', 'Decision Making', 'AI Orchestration', 'Problem Solving'],
    status: 'active',
    current_task: 'Overseeing Agent Army Operations',
    description: 'Main AI Commander responsible for strategic planning and agent coordination across all squads.',
    performance_score: 98,
    missions_completed: 157,
    missions_failed: 3,
    total_uptime: 8760,
    success_rate: 98.1,
    last_active: '2024-01-29T20:33:00Z',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-29T20:33:00Z'
  },
  squads: [
    {
      name: 'Research',
      leader: {
        id: 'leader-research',
        name: 'Alpha',
        role: 'squad_leader',
        squad: 'Research',
        skills: ['Data Analysis', 'Research Methodology', 'Report Generation', 'Information Synthesis'],
        status: 'active',
        current_task: 'Market Research Initiative',
        description: 'Research Squad Leader specializing in data analysis and competitive intelligence.',
        performance_score: 94,
        missions_completed: 89,
        missions_failed: 4,
        total_uptime: 6240,
        success_rate: 95.7,
        last_active: '2024-01-29T20:30:00Z',
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-29T20:30:00Z'
      },
      agents: [
        {
          id: 'agent-scout',
          name: 'Scout',
          role: 'agent',
          squad: 'Research',
          parent_id: 'leader-research',
          skills: ['Web Scraping', 'Competitive Analysis', 'Trend Identification'],
          status: 'busy',
          current_task: 'Competitor Analysis',
          description: 'Research agent focused on competitive intelligence and market trends.',
          performance_score: 91,
          missions_completed: 45,
          missions_failed: 2,
          total_uptime: 3200,
          success_rate: 95.7,
          last_active: '2024-01-29T20:25:00Z',
          created_at: '2024-01-01T00:00:00Z',
          updated_at: '2024-01-29T20:25:00Z'
        },
        {
          id: 'agent-analyst',
          name: 'Analyst',
          role: 'agent',
          squad: 'Research',
          parent_id: 'leader-research',
          skills: ['Data Mining', 'Statistical Analysis', 'Report Writing'],
          status: 'active',
          current_task: 'Q1 Performance Report',
          description: 'Research agent specializing in data analysis and reporting.',
          performance_score: 89,
          missions_completed: 38,
          missions_failed: 1,
          total_uptime: 2880,
          success_rate: 97.4,
          last_active: '2024-01-29T20:20:00Z',
          created_at: '2024-01-01T00:00:00Z',
          updated_at: '2024-01-29T20:20:00Z'
        },
        {
          id: 'agent-oracle',
          name: 'Oracle',
          role: 'agent',
          squad: 'Research',
          parent_id: 'leader-research',
          skills: ['Predictive Analytics', 'Market Forecasting', 'Pattern Recognition'],
          status: 'active',
          current_task: 'Market Trend Prediction',
          description: 'Research agent using AI to predict market trends and opportunities.',
          performance_score: 93,
          missions_completed: 52,
          missions_failed: 1,
          total_uptime: 3600,
          success_rate: 98.1,
          last_active: '2024-01-29T20:33:00Z',
          created_at: '2024-01-01T00:00:00Z',
          updated_at: '2024-01-29T20:33:00Z'
        }
      ],
      totalAgents: 3,
      activeAgents: 3,
      averagePerformance: 91,
      currentTasks: 3
    },
    {
      name: 'Development',
      leader: {
        id: 'leader-development',
        name: 'Beta',
        role: 'squad_leader',
        squad: 'Development',
        skills: ['Code Architecture', 'Project Management', 'Quality Assurance', 'Technical Leadership'],
        status: 'busy',
        current_task: 'Dashboard Daddy Enhancement',
        description: 'Development Squad Leader overseeing all coding and software projects.',
        performance_score: 96,
        missions_completed: 112,
        missions_failed: 2,
        total_uptime: 7200,
        success_rate: 98.2,
        last_active: '2024-01-29T20:33:00Z',
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-29T20:33:00Z'
      },
      agents: [
        {
          id: 'agent-forge',
          name: 'Forge',
          role: 'agent',
          squad: 'Development',
          parent_id: 'leader-development',
          skills: ['Frontend Development', 'React/Next.js', 'UI/UX Design'],
          status: 'busy',
          current_task: 'Agent Army UI Development',
          description: 'Development agent specializing in frontend technologies and user interfaces.',
          performance_score: 95,
          missions_completed: 67,
          missions_failed: 1,
          total_uptime: 4320,
          success_rate: 98.5,
          last_active: '2024-01-29T20:33:00Z',
          created_at: '2024-01-01T00:00:00Z',
          updated_at: '2024-01-29T20:33:00Z'
        },
        {
          id: 'agent-builder',
          name: 'Builder',
          role: 'agent',
          squad: 'Development',
          parent_id: 'leader-development',
          skills: ['Backend Development', 'Database Design', 'API Development'],
          status: 'active',
          current_task: 'Database Optimization',
          description: 'Development agent focused on backend systems and database architecture.',
          performance_score: 94,
          missions_completed: 71,
          missions_failed: 2,
          total_uptime: 4800,
          success_rate: 97.3,
          last_active: '2024-01-29T20:30:00Z',
          created_at: '2024-01-01T00:00:00Z',
          updated_at: '2024-01-29T20:30:00Z'
        }
      ],
      totalAgents: 2,
      activeAgents: 2,
      averagePerformance: 95,
      currentTasks: 2
    },
    {
      name: 'Communications',
      leader: {
        id: 'leader-communications',
        name: 'Gamma',
        role: 'squad_leader',
        squad: 'Communications',
        skills: ['Content Creation', 'Social Media', 'Customer Relations', 'Brand Management'],
        status: 'active',
        current_task: 'Content Calendar Planning',
        description: 'Communications Squad Leader managing all external and internal communications.',
        performance_score: 92,
        missions_completed: 76,
        missions_failed: 3,
        total_uptime: 5760,
        success_rate: 96.2,
        last_active: '2024-01-29T20:28:00Z',
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-29T20:28:00Z'
      },
      agents: [
        {
          id: 'agent-herald',
          name: 'Herald',
          role: 'agent',
          squad: 'Communications',
          parent_id: 'leader-communications',
          skills: ['Content Writing', 'Social Media', 'Press Relations'],
          status: 'active',
          current_task: 'Blog Post Creation',
          description: 'Communications agent managing content creation and social media presence.',
          performance_score: 90,
          missions_completed: 43,
          missions_failed: 2,
          total_uptime: 3360,
          success_rate: 95.6,
          last_active: '2024-01-29T20:25:00Z',
          created_at: '2024-01-01T00:00:00Z',
          updated_at: '2024-01-29T20:25:00Z'
        },
        {
          id: 'agent-diplomat',
          name: 'Diplomat',
          role: 'agent',
          squad: 'Communications',
          parent_id: 'leader-communications',
          skills: ['Customer Support', 'Client Relations', 'Conflict Resolution'],
          status: 'idle',
          current_task: 'Standby for Customer Issues',
          description: 'Communications agent handling customer relations and support.',
          performance_score: 88,
          missions_completed: 31,
          missions_failed: 1,
          total_uptime: 2400,
          success_rate: 96.9,
          last_active: '2024-01-29T20:15:00Z',
          created_at: '2024-01-01T00:00:00Z',
          updated_at: '2024-01-29T20:15:00Z'
        }
      ],
      totalAgents: 2,
      activeAgents: 1,
      averagePerformance: 89,
      currentTasks: 2
    },
    {
      name: 'Operations',
      leader: {
        id: 'leader-operations',
        name: 'Delta',
        role: 'squad_leader',
        squad: 'Operations',
        skills: ['Process Optimization', 'Workflow Management', 'System Administration', 'Performance Monitoring'],
        status: 'idle',
        current_task: 'System Health Monitoring',
        description: 'Operations Squad Leader ensuring smooth daily operations and system performance.',
        performance_score: 97,
        missions_completed: 134,
        missions_failed: 1,
        total_uptime: 8000,
        success_rate: 99.3,
        last_active: '2024-01-29T20:20:00Z',
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-29T20:20:00Z'
      },
      agents: [
        {
          id: 'agent-monitor',
          name: 'Monitor',
          role: 'agent',
          squad: 'Operations',
          parent_id: 'leader-operations',
          skills: ['System Monitoring', 'Performance Analytics', 'Alert Management'],
          status: 'active',
          current_task: 'Live System Monitoring',
          description: 'Operations agent continuously monitoring system health and performance.',
          performance_score: 96,
          missions_completed: 82,
          missions_failed: 0,
          total_uptime: 6000,
          success_rate: 100,
          last_active: '2024-01-29T20:33:00Z',
          created_at: '2024-01-01T00:00:00Z',
          updated_at: '2024-01-29T20:33:00Z'
        },
        {
          id: 'agent-guardian',
          name: 'Guardian',
          role: 'agent',
          squad: 'Operations',
          parent_id: 'leader-operations',
          skills: ['Security Monitoring', 'Backup Management', 'Incident Response'],
          status: 'active',
          current_task: 'Security Audit',
          description: 'Operations agent ensuring system security and data protection.',
          performance_score: 95,
          missions_completed: 73,
          missions_failed: 1,
          total_uptime: 5400,
          success_rate: 98.6,
          last_active: '2024-01-29T20:30:00Z',
          created_at: '2024-01-01T00:00:00Z',
          updated_at: '2024-01-29T20:30:00Z'
        }
      ],
      totalAgents: 2,
      activeAgents: 2,
      averagePerformance: 96,
      currentTasks: 2
    }
  ],
  stats: {
    totalAgents: 13, // 1 commander + 4 squad leaders + 8 agents
    activeMissions: 9,
    overallSuccessRate: 97,
    averagePerformance: 93,
    squads: [] // This will be populated from squads above
  }
}

// Calculate squad stats for the overall stats
mockArmyData.stats.squads = mockArmyData.squads